spring.application.name=workflow-engine
spring.datasource.url=jdbc:postgresql://localhost:5432/aop_db
spring.datasource.username=aop_user
spring.datasource.password=aop_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379
